// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb5ThQ-ytLHhN5Y4GyQNQyvvvZKY9fQQ8',
    appId: '1:28169414258:web:87b42fc6386d514b70c4eb',
    messagingSenderId: '28169414258',
    projectId: 'shop-ease-13fb5',
    authDomain: 'shop-ease-13fb5.firebaseapp.com',
    storageBucket: 'shop-ease-13fb5.appspot.com',
    measurementId: 'G-N6DEBJXMS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArm_aLy90eokRrs7XdE9hdFfM1MzY3yJk',
    appId: '1:28169414258:android:401bf5fcfc231f7370c4eb',
    messagingSenderId: '28169414258',
    projectId: 'shop-ease-13fb5',
    storageBucket: 'shop-ease-13fb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABGAZnmPsxjO0W989bNxE_7EkkIMIcKQ8',
    appId: '1:28169414258:ios:52d42c273556ab2970c4eb',
    messagingSenderId: '28169414258',
    projectId: 'shop-ease-13fb5',
    storageBucket: 'shop-ease-13fb5.appspot.com',
    iosBundleId: 'com.example.shopease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABGAZnmPsxjO0W989bNxE_7EkkIMIcKQ8',
    appId: '1:28169414258:ios:52d42c273556ab2970c4eb',
    messagingSenderId: '28169414258',
    projectId: 'shop-ease-13fb5',
    storageBucket: 'shop-ease-13fb5.appspot.com',
    iosBundleId: 'com.example.shopease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb5ThQ-ytLHhN5Y4GyQNQyvvvZKY9fQQ8',
    appId: '1:28169414258:web:ac9286f5de3d392570c4eb',
    messagingSenderId: '28169414258',
    projectId: 'shop-ease-13fb5',
    authDomain: 'shop-ease-13fb5.firebaseapp.com',
    storageBucket: 'shop-ease-13fb5.appspot.com',
    measurementId: 'G-WT2ZQQB3D5',
  );

}