// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZVgo--FI-FzWaCMdVBUMS4D-PVG3qWBI',
    appId: '1:161810860912:web:2bed292e4540ae2c6dddb5',
    messagingSenderId: '161810860912',
    projectId: 'eccomerce-app-68c2a',
    authDomain: 'eccomerce-app-68c2a.firebaseapp.com',
    storageBucket: 'eccomerce-app-68c2a.appspot.com',
    measurementId: 'G-RZJLYCB9BQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnfzwifR2T9-a253pcnSYZ0qLrXqdOjNQ',
    appId: '1:161810860912:android:071f207a6f349ece6dddb5',
    messagingSenderId: '161810860912',
    projectId: 'eccomerce-app-68c2a',
    storageBucket: 'eccomerce-app-68c2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3GSGnn9lJTVm4cN9_IR_LwMKAALVQLhY',
    appId: '1:161810860912:ios:d1773dd46be27ae76dddb5',
    messagingSenderId: '161810860912',
    projectId: 'eccomerce-app-68c2a',
    storageBucket: 'eccomerce-app-68c2a.appspot.com',
    iosBundleId: 'com.example.shopease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3GSGnn9lJTVm4cN9_IR_LwMKAALVQLhY',
    appId: '1:161810860912:ios:17dbd0876bd21d6c6dddb5',
    messagingSenderId: '161810860912',
    projectId: 'eccomerce-app-68c2a',
    storageBucket: 'eccomerce-app-68c2a.appspot.com',
    iosBundleId: 'com.example.shopease.RunnerTests',
  );
}
